import { SanityLive } from "@/sanity/lib/live";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Quollex | Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        >
        {children}
        <SanityLive/>
      </body>
    </html>

 
  );
}
